@url = http://localhost:8000/api/v1/user


POST  {{url}}/register

Content-Type:application/json

{
    "name":"shop typescript",
    "email":"shoptype@gmail.com",
    "password":"123456789"
}


###
GET http://localhost:8000